#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'admin-models'
  description: 'Tailormap admin API models'
  version: '1.0'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

components:
  schemas:
    ServerSentEvent:
      description: 'Server sent event'
      type: object
      properties:
        eventType:
          type: string
          description: 'Type of event'
          enum: [ 'keep-alive', 'entity-created', 'entity-deleted', 'entity-updated', 'task-progress' ]
        details:
          type: object

    EntityEvent:
      type: object
      properties:
        entityName:
          type: string
        id:
          type: string
        object:
          description: 'The entity in JSON, only included in created and updated events.'
          type: object

    TaskProgressEvent:
      description: 'Task progress event. This event is sent when a _running_ task makes progress, including start/stop. 
                    The fraction of the task that is done can be computed using `progress` and `total` (if not null).'
      type: object
      required:
        - 'type'
        - 'uuid'
        - 'progress'
      properties:
        type:
          description: 'Type of the task.'
          type: string
          nullable: false
          example: 'index'
        uuid:
          description: 'UUID of the task; this, combined with type, is used to uniquely identify the task.'
          type: string
          format: uuid
          nullable: false
        total:
          description: 'Total number of items to process. May be `null` or empty if unknown.'
          type: integer
          # note that this is limited by the GeoTools API, which uses an int for the number of features in a feature collection
          format: int32
          nullable: true
          example: 1200
        progress:
          description: 'Number of items processed so far.'
          type: integer
          format: int32
          default: 0
          example: 113
        startedAt:
          description: 'Timestamp when the task started.'
          type: string
          format: date-time
          nullable: true
          example: '2021-06-01T12:34:56Z'

    TaskSchedule:
      type: object
      required:
        - cronExpression
      properties:
        uuid:
          description: 'UUID of the task; this is the unique identifier of the task'
          type: string
          format: uuid
          readOnly: true
          nullable: true
        description:
          description: 'Human-readable description of the task.'
          type: string
          nullable: true
        cronExpression:
          description: 'Cron expression for the task'
          type: string
          nullable: false
        priority:
          description: 'Priority of the task'
          type: integer
          nullable: true
