#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'models'
  description: 'Tailormap API models common to the persistence layer and the API.'
  version: '1.0'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

# The openapi-generator plugin is run twice: once for the persistence layer JSON and once for the
# models used in the API. Specify all common models in <importMappings> for the second run so common
# models use the same class, and add them to the common-schemas-openapi-ignore file.

components:
  schemas:
    GeoServiceProtocol:
      type: string
      description: Note that the values are case-insensitive and that `legend` is a pseudo-protocol for proxying legend requests.
      enum:
        - wms
        - wmts
        - xyz
        - tiles3d
        - quantizedmesh
        - legend
      # force the enum variable names to be uppercase without underscores
      # see:
      #  https://github.com/OpenAPITools/openapi-generator/issues/19086
      #  https://github.com/OpenAPITools/openapi-generator/issues/19066
      x-enum-varnames:
        - WMS
        - WMTS
        - XYZ
        - TILES3D
        - QUANTIZEDMESH
        - LEGEND

    TileLayerHiDpiMode:
      type: string
      enum: # Tiles are DPI-independent, for example an orthofoto - just show the next zoom level at
        # high DPI.
        - showNextZoomLevel
        # Substitute a layer which renders features larger (using more pixels for lines, labels,
        # etc.) but show a deeper zoomlevel of the substituted layer.
        - substituteLayerShowNextZoomLevel
        # Show the same zoomlevel of the substituted layer but set tilePixelRatio to 2: the layer
        # must be a 2x sized tile compared to the size in the capabilities
        - substituteLayerTilePixelRatioOnly
      # force the enum variable names to be uppercase without underscores
      # see:
      #  https://github.com/OpenAPITools/openapi-generator/issues/19086
      #  https://github.com/OpenAPITools/openapi-generator/issues/19066
      x-enum-varnames:
        - SHOWNEXTZOOMLEVEL
        - SUBSTITUTELAYERSHOWNEXTZOOMLEVEL
        - SUBSTITUTELAYERTILEPIXELRATIOONLY

    Bounds:
      description: 'Bounds without the context of a coordinate reference system'
      type: object
      x-class-extra-annotation: '@jakarta.persistence.Embeddable'
      properties:
        miny:
          description: 'lower bottom'
          type: number
          format: double
        minx:
          description: 'lower left'
          type: number
          format: double
        maxy:
          description: 'upper top'
          type: number
          format: double
        maxx:
          description: 'upper right'
          type: number
          format: double
      required:
        - miny
        - minx
        - maxy
        - maxx
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000

    # XXX: currently unused
    BoundsWithCRS:
      description: 'Bounds within the context of a coordinate reference system'
      allOf:
        - $ref: '#/components/schemas/Bounds'
        - type: object
          required: [crs]
          properties:
            crs:
              description: '(EPSG) code of the projection'
              type: string
              nullable: false
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000
        crs: 'EPSG:28992'

    TMGeometryType:
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point

    TMAttributeType:
      description: 'data type. eg "date" or "string".
          see also: org.tailormap.api.persistence.TMAttributeDescriptor'
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point
        - boolean
        - integer
        - string
        - double
        - date
        - timestamp
        - object

    WMSStyle:
      type: object
      required: [name]
      properties:
        name:
          type: string
          nullable: false
        title:
          type: string
        abstractText:
          type: string
        legendURL:
          type: string
          format: uri

    AppI18nSettings:
      title: AppI18nSettings
      type: object
      required:
        - defaultLanguage
        - hideLanguageSwitcher
      properties:
        defaultLanguage:
          type: string
          nullable: true
        hideLanguageSwitcher:
          nullable: false
          type: boolean

    AppUiSettings:
      title: AppUiSettings
      type: object
      required:
        - hideLoginButton
        - enable3D
      properties:
        hideLoginButton:
          nullable: false
          type: boolean
        enable3D:
          nullable: false
          type: boolean

    FilterGroup:
      title: FilterGroup
      description: A group of filters. The group can be used to group filters together, or to disable a group of filters.
      type: object
      properties:
        id:
          description: 'id of the filter group'
          type: string
          nullable: false
        source:
          description: 'source of the filter group'
          type: string
          nullable: false
        layerIds:
          description: 'list of layer ids'
          type: array
          items:
            type: string
          minItems: 1
        type:
          description: NOTE spatial is not supported (for now) for preconfigured filters
          enum:
            - ATTRIBUTE
        #   - SPATIAL
        operator:
          description: The operator for the filter group, we may want to support the OR operator in the future
          enum:
            - AND
            - OR
          default: AND
        filters:
          description: A list of filters
          type: array
          items:
            $ref: '#/components/schemas/Filter'
          minItems: 1
        disabled:
          type: boolean
          nullable: true
        parentGroup:
          type: string
          nullable: true

    Filter:
      title: Filter
      description: A filter for an attribute. The filter can be used to filter the features of a layer, based on attribute value
      type: object
      properties:
        id:
          description: 'id of the filter'
          type: string
          nullable: false
        type:
          description: 'type of the filter'
          enum:
            - ATTRIBUTE
          # NOTE spatial is not supported (for now) for preconfigured filters
          # - SPATIAL
        condition:
          enum:
            - 'UNIQUE_VALUES'
            - '='
            - '<>'
            - '>'
            - '<'
            - '>='
            - '<='
            - '><'
            - 'EQUALS'
            - 'LIKE'
            - 'STARTS_WITH'
            - 'ENDS_WITH'
            - 'ON'
            - 'AFTER'
            - 'BEFORE'
            - 'BETWEEN'
            - 'TRUE'
            - 'FALSE'
            - 'NULL'
        #   - 'INTERSECTS' spatial not supported (for now)
        invertCondition:
          description: 'when true the condition is to be inverted'
          type: boolean
          nullable: false
          default: false
        attribute:
          description: 'name of the attribute'
          type: string
          nullable: false
        attributeType:
          description: 'type of the attribute'
          enum:
            - date
            - timestamp
            - string
            - double
            - number
            - integer
            - boolean
        # spatial not supported (for now)
        #   - linestring
        #   - multilinestring
        #   - point
        #   - multipoint
        #   - polygon
        #   - multipolygon
        #   - geometry
        #   - geometry_collection
        value:
          description: 'value of the filter'
          type: array
          items:
            type: string
            minItems: 1
        caseSensitive:
          description: 'true when the filter is case sensitive'
          type: boolean
          nullable: false
          default: false
        editConfiguration:
          description: 'configuration for editing filter'
          allOf:
            - type: object
              properties:
                filterTool:
                  description: 'the type of filter tool'
                  enum:
                    - 'SLIDER'
                    - 'CHECKBOX'
                    - 'SWITCH'
                    - 'DATE_PICKER'
                    - 'DROPDOWN_LIST'
            - anyOf:
                - $ref: '#/components/schemas/SliderFilterConfiguration'
                - $ref: '#/components/schemas/CheckboxDropdownListFilterConfiguration'
                - $ref: '#/components/schemas/SwitchFilterConfiguration'
                - $ref: '#/components/schemas/DatePickerFilterConfiguration'

    SliderFilterConfiguration:
      title: SliderFilterConfiguration
      description: Configuration for a slider filter
      type: object
      properties:
        minimumValue:
          description: 'minimum value for the slider'
          type: number
          format: double
        maximumValue:
          description: 'maximum value for the slider'
          type: number
          format: double
        initialValue:
          description: 'initial value for the slider'
          type: number
          format: double
        initialLowerValue:
          description: 'initial lower value for a slider filter with between condition'
          type: number
          format: double
        initialUpperValue:
          description: 'initial upper value for a slider filter with between condition'
          type: number
          format: double
        inputMode:
          description: 'the mode of input for the filter'
          enum:
            - 'SLIDER'
            - 'INPUT_FIELD'
            - 'SLIDER_AND_INPUT_FIELD'
          default: 'SLIDER'

    CheckboxDropdownListFilterConfiguration:
      title: CheckboxDropdownListFilterConfiguration
      description: Configuration for a checkbox filter or a dropdown list filter
      type: object
      properties:
        attributeValuesSettings:
            description: 'settings for the attribute values'
            type: array
            items:
              type: object
              title: AttributeValueSettings
              properties:
                value:
                  type: string
                  required: true
                initiallySelected:
                  type: boolean
                  default: true
                selectable:
                  type: boolean
                  default: true
                alias:
                  type: string
                substringFilter:
                  description: 'Use this value as a substring filter'
                  type: boolean
                  default: false

    SwitchFilterConfiguration:
      title: BooleanFilterConfiguration
      description: Configuration for a boolean filter
      type: object
      properties:
        value1:
          type: string
        value2:
          type: string
        alias1:
          type: string
        alias2:
          type: string
        startWithValue2:
          description: 'when true the filter starts with value2 selected'
          type: boolean
          default: false

    DatePickerFilterConfiguration:
      title: DateFilterConfiguration
      description: Configuration for a date filter
      type: object
      properties:
        initialDate:
          description: 'initial value for the date filter'
          type: string
          format: date-time
        initialLowerDate:
          description: 'initial lower value for a date filter with between condition'
          type: string
          format: date-time
        initialUpperDate:
          description: 'initial upper value for a date filter with between condition'
          type: string
          format: date-time

    FormOptions:
      description: 'model with options for an form'
      type: object
      properties:
        description:
          description: 'description text for the form'
          type: string
          nullable: true
        columns:
          description: 'the number of columns (adjusts the width of the form)'
          type: integer
          format: int32
        tabs:
          description: 'list of tabs for a form'
          type: array
          items:
            type: object
            title: FormTab
            properties:
              id:
                description: 'id of the tab'
                type: string
              name:
                description: 'title of the tab'
                type: string

    FormField:
      description: 'model for a single form field'
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        type:
          enum:
            - text
            - number
            - integer
            - boolean
            - select
            - textarea
            - date
            - timestamp
        tab:
          type: string
          nullable: true
        column:
          type: number
          nullable: true
        uniqueValuesAsOptions:
          description: 'when true the unique values for the column are used when editing this field'
          type: boolean
          nullable: true
        valueList:
          type: array
          nullable: true
          items:
            type: object
            title: FormFieldValue
            properties:
              value:
                type: string
              label:
                type: string
        allowValueListOnly:
          type: boolean
          nullable: true
        disabled:
          type: boolean
          nullable: true
        required:
          type: boolean
          nullable: true
        autoFillUser:
          type: boolean
          nullable: true
        autoFillDate:
          type: boolean
          nullable: true
        placeholder:
          type: string
          nullable: true
        hint:
          type: string
          nullable: true

    HiddenLayerFunctionality:
      description: Functionality that should be hidden for a layer in the UI. The functionality is still available in the backend, so not a "security" setting.
      type: array
      uniqueItems: true
      items:
        $ref: '#/components/schemas/HiddenLayerFunctionalityEnum'

    HiddenLayerFunctionalityEnum:
      type: string
      enum:
        - "feature-info"
        - "attribute-list"
        - "export"
