#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'models'
  description: 'Tailormap API models common to the persistence layer and the API.'
  version: '1.0'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

# The openapi-generator plugin is run twice: once for the persistence layer JSON and once for the
# models used in the API. Specify all common models in <importMappings> for the second run so common
# models use the same class, and add them to the common-schemas-openapi-ignore file.

components:
  schemas:
    GeoServiceProtocol:
      type: string
      description: Note that the values are case-insensitive and that `proxiedlegend` is a pseudo-protocol for proxied legend requests.
      enum:
        - wms
        - wmts
        - xyz
        - tiles3d
        - quantizedmesh
        - proxiedlegend
      # force the enum variable names to be uppercase without underscores
      # see:
      #  https://github.com/OpenAPITools/openapi-generator/issues/19086
      #  https://github.com/OpenAPITools/openapi-generator/issues/19066
      x-enum-varnames:
        - WMS
        - WMTS
        - XYZ
        - TILES3D
        - QUANTIZEDMESH
        - PROXIEDLEGEND

    TileLayerHiDpiMode:
      type: string
      enum: # Tiles are DPI-independent, for example an orthofoto - just show the next zoom level at
        # high DPI.
        - showNextZoomLevel
        # Substitute a layer which renders features larger (using more pixels for lines, labels,
        # etc.) but show a deeper zoomlevel of the substituted layer.
        - substituteLayerShowNextZoomLevel
        # Show the same zoomlevel of the substituted layer but set tilePixelRatio to 2: the layer
        # must be a 2x sized tile compared to the size in the capabilities
        - substituteLayerTilePixelRatioOnly
      # force the enum variable names to be uppercase without underscores
      # see:
      #  https://github.com/OpenAPITools/openapi-generator/issues/19086
      #  https://github.com/OpenAPITools/openapi-generator/issues/19066
      x-enum-varnames:
        - SHOWNEXTZOOMLEVEL
        - SUBSTITUTELAYERSHOWNEXTZOOMLEVEL
        - SUBSTITUTELAYERTILEPIXELRATIOONLY

    Bounds:
      description: 'Bounds without the context of a coordinate reference system'
      type: object
      x-class-extra-annotation: '@jakarta.persistence.Embeddable'
      properties:
        miny:
          description: 'lower bottom'
          type: number
          format: double
        minx:
          description: 'lower left'
          type: number
          format: double
        maxy:
          description: 'upper top'
          type: number
          format: double
        maxx:
          description: 'upper right'
          type: number
          format: double
      required:
        - miny
        - minx
        - maxy
        - maxx
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000

    # XXX: currently unused
    BoundsWithCRS:
      description: 'Bounds within the context of a coordinate reference system'
      allOf:
        - $ref: '#/components/schemas/Bounds'
        - type: object
          required: [crs]
          properties:
            crs:
              description: '(EPSG) code of the projection'
              type: string
              nullable: false
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000
        crs: 'EPSG:28992'

    TMGeometryType:
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point

    TMAttributeType:
      description: 'data type. eg "date" or "string".
          see also: org.tailormap.api.persistence.TMAttributeDescriptor'
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point
        - boolean
        - integer
        - string
        - double
        - date
        - timestamp
        - object

    WMSStyle:
      type: object
      required: [name]
      properties:
        name:
          type: string
          nullable: false
        title:
          type: string
        abstractText:
          type: string
        legendURL:
          type: string
          format: uri

    AppI18nSettings:
      title: AppI18nSettings
      type: object
      required:
        - defaultLanguage
        - hideLanguageSwitcher
      properties:
        defaultLanguage:
          type: string
          nullable: true
        hideLanguageSwitcher:
          nullable: false
          type: boolean

    AppUiSettings:
      title: AppUiSettings
      type: object
      required:
        - hideLoginButton
        - enable3D
      properties:
        hideLoginButton:
          nullable: false
          type: boolean
        enable3D:
          nullable: false
          type: boolean

    FormOptions:
      description: 'model with options for an form'
      type: object
      properties:
        description:
          description: 'description text for the form'
          type: string
          nullable: true
        columns:
          description: 'the number of columns (adjusts the width of the form)'
          type: integer
          format: int32
        tabs:
          description: 'list of tabs for a form'
          type: array
          items:
            type: object
            title: FormTab
            properties:
              id:
                description: 'id of the tab'
                type: string
              name:
                description: 'title of the tab'
                type: string

    FormField:
      description: 'model for a single form field'
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        type:
          enum:
            - text
            - number
            - integer
            - boolean
            - select
            - textarea
            - date
            - timestamp
        tab:
          type: string
          nullable: true
        column:
          type: number
          nullable: true
        uniqueValuesAsOptions:
          description: 'when true the unique values for the column are used when editing this field'
          type: boolean
          nullable: true
        valueList:
          type: array
          nullable: true
          items:
            type: object
            title: FormFieldValue
            properties:
              value:
                type: string
              label:
                type: string
        allowValueListOnly:
          type: boolean
          nullable: true
        disabled:
          type: boolean
          nullable: true
        required:
          type: boolean
          nullable: true
        placeholder:
          type: string
          nullable: true
        hint:
          type: string
          nullable: true
