#
# Copyright (C) 2026 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.4
info:
  title: 'obsolete viewer models'
  description: 'no servers or paths, just obsolete models in this document that need to be generated for backwards 
              compatibility, but should not be used in the API anymore.'
  version: '1.0'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'
servers: [ ]
paths: { }

components:
  schemas:
    LayerExportCapabilities:
      description: '**OBSOLETE**, since the export capabilities are now predefined and no longer need to be discovered per layer'
      type: object
      required: [exportable]
      properties:
        exportable:
          nullable: false
          type: boolean
        outputFormats:
          type: array
          items:
            type: string