#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.4

info:
  title: 'status responses'
  description: 'Tailormap status API decribes generic responses.'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  version: '1.0'

servers: [ ]
paths: { }

components:
  schemas:
    RedirectResponse:
      description: '
      login required response, but can also be used for other response that require redirection.
      Does not include a HTTP header to force redirection, but a url that the client can use.
      '
      type: object
      properties:
        code:
          type: integer
          format: int32
          default: 401
        url:
          description: 'redirect url'
          type: string
          default: '/login'
      example:
        code: 401
        message: 'login required'
        url: '/login'


    ErrorResponse:
      description: '
      General server error response. Can be returned when something goes terribly wrong in the backend.
      **Note** that the diagnostic message may be of a general character to prevent disclosure of information about the backend.
      Error codes are defined in the [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) standard, 
      and can range from 400 to 599.
      '
      type: object
      properties:
        code:
          type: integer
          format: int32
          default: 500
        message:
          description: 'diagnostic message'
          type: string
          default: 'Internal server error'
      example:
        code: 500
        message: 'Internal server error'

    ServerSentEventResponse:
      description: 'Server Sent Event response. 
      The client can use the `eventType` property to determine the type of event, and the `details` property 
      to get specific event data.'
      type: object
      required:
        - eventType
      properties:
        eventType:
          description: 'Event type'
          type: string
        details:
          description: 'Event data. Can be any JSON object or nothing, but should include at least a `status` property to indicate the status of the event.'
          type: object
          nullable: true
        id:
          description: 'optional event identifier, can be used for event ordering and deduplication'
          type: string
          format: uuid
          nullable: true
      example:
        eventType: 'extract-started'
        details:
          status: 'started'
          message: 'Extracting data'
          progress: 10
        id: '123e4567-e89b-12d3-a456-426614174000'
