# This profile is for PR deployments just serving a different static Angular frontend built with a
# different BASE_HREF, which is hardcoded to use the /api path. So this profile should not connect
# to the database or enable any controllers because the frontend will use the /api from the
# tailormap running on /.

tailormap-api.static-only=true

# serve static frontend from this directory (/home/spring is the workdir in Dockerfile)
spring.web.resources.static-locations=file:/home/cnb/static/,classpath:/static/

spring.main.banner-mode=off
spring.autoconfigure.exclude[0]=org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.security.autoconfigure.actuate.web.servlet.ManagementWebSecurityAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.autoconfigure.exclude[3]=org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[4]=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
spring.autoconfigure.exclude[5]=org.springframework.boot.quartz.autoconfigure.QuartzAutoConfiguration

management.endpoints.access.default=none
management.endpoints.web.exposure.exclude=*
