create table page (
    id bigint generated by default as identity,
    class_name varchar(255),
    content text,
    name varchar(255) not null,
    tiles jsonb,
    title varchar(255),
    type varchar(255),
    version bigint,
    primary key (id)
);

alter table if exists page
   add constraint name_unique unique (name);
