create table oidcconfiguration (
  id int8 generated by default as identity,
  version int8,
  name text not null,
  client_id text not null,
  client_secret text,
  issuer_url text not null,
  user_name_attribute text not null,
  status text
);
